Libft: src/ft_printf/ft_printf.c File Reference
ft_printf.c File Reference
#include "../include/ft_printf.h"
Functions
static void parse_conv (char coversion, int *res, va_list args)
int ft_printf (const char *format,...)
Function Documentation
ft_printf()
int ft_printf (const char * format, ...)
Definition at line 17 of file ft_printf.c.
{
    va_list args;
    int     ret;
    va_start(args, format);
    ret = 0;
    while (*format)
    {
        if (*format == '%' && *(format + 1) != '\0')
        {
            parse_conv(*(format + 1), &ret, args);
            format++;
        }
        else if (!(*format == '%' && *(format + 1) == '\0'))
        {
            write(1, format, 1);
            ret++;
        }
        format++;
    }
    va_end(args);
    return (ret);
}
References parse_conv().
parse_conv()
static void parse_conv (char coversion, int * res, va_list args) static
Definition at line 42 of file ft_printf.c.
{
    if (conversion == 'c')
        printchar(res, va_arg(args, int));
    else if (conversion == '%')
        printchar(res, '%');
    else if (conversion == 's')
        printstr(res, va_arg(args, char *));
    else if (conversion == 'i' || conversion == 'd')
        printnum(res, va_arg(args, int));
    else if (conversion == 'x' || conversion == 'X')
        printbase(res, va_arg(args, unsigned int), 16, conversion == 'X');
    else if (conversion == 'u')
        printbase(res, va_arg(args, unsigned int), 10, 0);
    else if (conversion == 'p')
        printptr(res, va_arg(args, void *));
}
References printbase(), printchar(), printnum(), printptr(), and printstr().
Referenced by ft_printf().