Libft: src/stdlibft/ft_strnstr.c File Reference
ft_strnstr.c File Reference
#include "../include/libft.h"
Functions
static int ft_loop (size_t i, size_t len, const char *needle)
char * ft_strnstr (const char *haystack, const char *needle, size_t len)
Function Documentation
ft_loop()
static int ft_loop (size_t i, size_t len, const char * needle) static
Definition at line 42 of file ft_strnstr.c.
{
    if (len == (size_t) -1)
        return (1);
    if (len < ft_strlen(needle))
        return (0);
    if (i < len - ft_strlen(needle) + 1)
        return (1);
    return (0);
}
References ft_strlen().
Referenced by ft_strnstr().
ft_strnstr()
char * ft_strnstr (const char * haystack, const char * needle, size_t len)
Definition at line 17 of file ft_strnstr.c.
{
    size_t          i;
    unsigned long   hs;
    char            *found;
    const char      *nd;
    i = 0;
    hs = (unsigned long) haystack;
    if (*needle == '\0' || haystack == needle)
        return ((char *) hs);
    if (*haystack == 0)
        return (NULL);
    while (*(char *)hs != '\0' && ft_loop(i++, len, needle))
    {
        nd = needle;
        found = (char *) hs;
        while (*nd++ == *found++)
            if (*nd == '\0')
                return ((char *) hs);
        hs++;
    }
    return (NULL);
}
References ft_loop().