Libft: src/stdlibft/ft_strlcpy.c File Reference
ft_strlcpy.c File Reference
#include "../include/libft.h"
Functions
size_t ft_strlcpy (char *dst, const char *src, size_t dstsize)
Function Documentation
ft_strlcpy()
size_t ft_strlcpy (char * dst, const char * src, size_t dstsize)
Definition at line 15 of file ft_strlcpy.c.
{
    const char  *s;
    size_t      i;
    s = src;
    i = 0;
    if (dstsize == 0)
        return (ft_strlen(s));
    while (*src && i++ < dstsize - 1)
        *dst++ = *src++;
    *dst = '\0';
    return (ft_strlen(s));
}
References ft_strlen().
Referenced by ft_split(), ft_strjoin(), ft_substr(), and return_result().