Libft: src/stdlibft/ft_strlen.c File Reference
ft_strlen.c File Reference
#include "../include/libft.h"
Functions
size_t ft_strlen (const char *s)
Returns the number of characters in the string s.
Function Documentation
ft_strlen()
size_t ft_strlen (const char * s)
Returns the number of characters in the string s.
It takes a string s as a parameter and counts the number of characters thatt string has, then returns it as a size_t (unsigned long).
Parameters
s the string whose length will be measured
Returns
The length of the string
Definition at line 15 of file ft_strlen.c.
{
    size_t  len;
    len = 0;
    while (s && *s++)
        len++;
    return (len);
}
Referenced by clean_static(), create_return(), ft_append(), ft_hmap_delete(), ft_hmap_edit(), ft_hmap_get(), ft_loop(), ft_preppend(), ft_ptr_strnjoin(), ft_putstr_fd(), ft_putsubstr_fd(), ft_strdup(), ft_strjoin(), ft_strlcat(), ft_strlcpy(), ft_strmapi(), ft_strrchr(), ft_strtrim(), ft_substr(), and printstr().