Libft: src/stdlibft/ft_putsubstr_fd.c File Reference
ft_putsubstr_fd.c File Reference
#include "../include/libft.h"
Functions
int ft_putsubstr_fd (const char *str, size_t start, size_t end, int fd)
Prints a substring to the designated fd.
Function Documentation
ft_putsubstr_fd()
int ft_putsubstr_fd (const char * str, size_t start, size_t end, int fd)
Prints a substring to the designated fd.
Prints a subset of a string to the provided file descriptor. The substring contains all characters from the start position to the end position, both included.
Parameters
str the string from which to print the substring
start the index of the first char of the substring
end the index of the last char of the substring
fd the file destriptor to print to
Returns
The number of characters that where printed to the fd
Definition at line 15 of file ft_putsubstr_fd.c.
{
    char    *sub;
    int     ret;
    if (!str)
        return (0);
    sub = ft_substr(str, start, end - start + 1);
    if (!sub)
        return (0);
    ft_putstr_fd(sub, fd);
    ret = (int) ft_strlen(sub);
    ft_free((void **) &sub);
    return (ret);
}
References ft_free(), ft_putstr_fd(), ft_strlen(), and ft_substr().