Libft: src/include/get_next_line.h File Reference
get_next_line.h File Reference
#include "libft.h"
Macros
#define BUFFER_SIZE 42
Functions
char * get_next_line (int fd)
Returns the next line of an opened file.
char * ft_ptr_strnjoin (char const *s1, char const *s2, int chars_read)
Creates a new string with the concatenation of s1 + s2.
size_t ft_idx_strchr (const char *s, int c)
Returns the index of the first ocurrence of a character.
Macro Definition Documentation
BUFFER_SIZE
#define BUFFER_SIZE 42
Definition at line 17 of file get_next_line.h.
Referenced by get_next_line(), and read_line().
Function Documentation
ft_idx_strchr()
size_t ft_idx_strchr (const char * s, int c)
Returns the index of the first ocurrence of a character.
This is a modified version of ft_strchr that returns an index of type size_t of the first ocurrence of the character passed as parameter, instead of a pointer to the first ocurrence of that char.
Parameters
s the string that will be read
c the char that will be found, passed as int
Returns
The index of the first occurrence of c
Definition at line 39 of file get_next_line_utils.c.
{
    unsigned char   ch;
    int             i;
    ch = (unsigned char) c;
    i = 0;
    while (s[i] != '\0')
    {
        if (s[i++] == ch)
            return (--i);
    }
    if (ch == '\0')
        return (i);
    return (-1);
}
Referenced by create_return(), and read_line().
ft_ptr_strnjoin()
char * ft_ptr_strnjoin (char const * s1, char const * s2, int chars_read)
Creates a new string with the concatenation of s1 + s2.
This is a modified version of my libft's strjoin. It returns a new string consisting of all the content of s1 followed by the chars_read first chars of s2. The return is then null-terminated. Note: in this project, chars_read is the return value of read().
Parameters
s1 the first string that will be copied
s2 the secondd string that will be concatenated
chars_read the number of chars from s2 that will be concatenated
Returns
A new string consisting of s1 + s2
Definition at line 15 of file get_next_line_utils.c.
{
    size_t  total_size;
    char    *ret;
    if (!s1 || !s2 || chars_read < 0)
        return (NULL);
    total_size = ft_strlen(s2);
    if (total_size > (size_t) chars_read)
        total_size = chars_read;
    total_size += ft_strlen(s1) + 1;
    ret = ft_calloc(total_size, sizeof (char));
    if (!ret)
        return (NULL);
    while (*s1)
        *ret++ = *s1++;
    while (*s2 && chars_read > 0)
    {
        *ret++ = *s2++;
        chars_read--;
    }
    return (ret - total_size + 1);
}
References ft_calloc(), and ft_strlen().
Referenced by joinfree().
get_next_line()
char * get_next_line (int fd)
Returns the next line of an opened file.
get_next_line is the main function of the GNL 42Madrid project. It reads a file via a file descriptor and then returns a string with the first line it reads. In an error is encountered, it returns NULL.
Parameters
fd the file descriptor to read from
Returns
The first line of the file pointed by fd
Definition at line 77 of file get_next_line.c.
{
    static char *str;
    char        *ret;
    if (fd < 0 || BUFFER_SIZE <= 0 || read(fd, 0, 0) < 0)
    {
        ft_free((void **) &str);
        return (NULL);
    }
    if (!str)
    {
        str = ft_calloc(BUFFER_SIZE + 1, sizeof (char));
        if (!str)
            return (NULL);
    }
    str = read_line(fd, str);
    if (!str)
        return (NULL);
    ret = create_return(str);
    if (!ret)
        return (ft_free((void **) &str), NULL);
    str = clean_static(str);
    return (ret);
}
References BUFFER_SIZE, clean_static(), create_return(), ft_calloc(), ft_free(), and read_line().