Libft: src/include/libft.h File Reference
libft.h File Reference
This is libft's most important header file.
#include <stdlib.h>
#include <unistd.h>
Data Structures
struct s_list
struct s_key_value
struct s_hashmap
Macros
#define HASHMAP_DEFAULT_SIZE 20
#define HASHMAP_MAX_LOAD 0.75f
#define HASHMAP_RESIZE_FACTOR 2
Typedefs
typedef unsigned short t_ushort
typedef struct s_list t_list
typedef struct s_key_value t_key_value
typedef struct s_hashmap t_hashmap
Functions
int ft_toupper (int c)
Return the uppercase version of char c.
int ft_tolower (int c)
Return the lowercase version of char c.
int ft_isupper (int c)
Returns 1 if c is an uppercase letter.
int ft_isalpha (int c)
Returns 1 if c is an alphabetic character.
int ft_isdigit (int c)
Returns 1 if c is a digit (0-9).
int ft_isalnum (int c)
Returns 1 if c is an alphanumeric character.
int ft_isascii (int c)
Returns 1 if c is part of the ASCII table.
int ft_isspace (int c)
Returns 1 if c is a spacing character.
int ft_isprint (int c)
Returns 1 if c is a printable character.
int ft_islower (int c)
Returns 1 if c is a lowercase letter.
char * ft_strchr (const char *s, int c)
Returns a pointer to the first occurrence of a character.
char * ft_strrchr (const char *s, int c)
Returns a pointer to the last occurrence of a character.
size_t ft_strlen (const char *s)
Returns the number of characters in the string s.
int ft_strncmp (const char *s1, const char *s2, size_t n)
void * ft_memset (void *b, int c, size_t len)
void * ft_memchr (const void *s, int c, size_t n)
void ft_bzero (void *s, size_t n)
void * ft_memcpy (void *dst, const void *src, size_t n)
int ft_memcmp (const void *s1, const void *s2, size_t n)
void * ft_memmove (void *dst, const void *src, size_t n)
size_t ft_strlcpy (char *dst, const char *src, size_t dstsize)
size_t ft_strlcat (char *dst, const char *src, size_t dstsize)
char * ft_strnstr (const char *haystack, const char *needle, size_t len)
int ft_atoi (const char *str)
void * ft_calloc (size_t count, size_t size)
void ft_free (void **ptr)
char * ft_strdup (const char *s1)
char * ft_substr (const char *s, unsigned int start, size_t len)
char * ft_strjoin (const char *s1, const char *s2)
char * ft_strtrim (const char *s1, const char *set)
char * ft_preppend (const char *str, const char *pre, int fr_s, int fr_p)
char * ft_append (const char *str, const char *apd, int fr_s, int fr_a)
char * ft_strinsert (const char *str, const char *ins, size_t pos)
char ** ft_split (const char *s, char c)
char * ft_itoa (int n)
char * ft_ltoa (long n)
char * ft_strmapi (const char *s, char(*f)(unsigned int, char))
char * ft_striteri (char *s, void(*f)(unsigned int, char *))
int ft_putchar_fd (char c, int fd)
int ft_putstr_fd (const char *s, int fd)
int ft_putsubstr_fd (const char *str, size_t start, size_t end, int fd)
Prints a substring to the designated fd.
int ft_putendl_fd (const char *s, int fd)
int ft_putnbr_fd (int n, int fd)
int ft_lstsize (t_list *lst)
t_list * ft_lstnew (void *content)
t_list * ft_lstlast (t_list *lst)
void ft_lstadd_front (t_list **lst, t_list *new_lmn)
Adds an element to the start of the list.
void ft_lstadd_back (t_list **lst, t_list *new_lmn)
Adds an element to the end of the list.
void ft_lstdelone (t_list *lst, void(*del)(void *))
void ft_lstclear (t_list **lst, void(*del)(void *))
void ft_lstiter (t_list *lst, void(*f)(void *))
t_list * ft_lstmap (t_list *lst, void *(*f)(void *), void(*del)(void *))
t_hashmap * ft_hmap_new (void(*del)(void *))
void ft_hmap_free (t_hashmap *hmap)
t_hashmap * ft_hmap_resize (t_hashmap *hmap)
void ft_hmap_add (t_hashmap *hmap, void *key, void *value, size_t len)
void ft_hmap_delete (t_hashmap *hmap, void *key, size_t len)
t_ushort ft_hash (unsigned char *key, size_t nbytes)
void * ft_hmap_get (t_hashmap *hmap, void *key, size_t len)
void ft_hmap_edit (t_hashmap *hmap, void *key, void *value, size_t len)
int ft_trgb (int t, int r, int g, int b)
Creates an int representation of a trgb color. Takes four int components of a trgb color that must be between 0 and 255. Anything greater will break the function.
int ft_get_t (int trgb)
Returns the t component of the trgb color. Takes an int representation of a trgb color as parameter. Retuns that color's transparency component.
int ft_get_r (int trgb)
Returns the r component of the trgb color. Takes an int representation of a trgb color as parameter. Retuns that color's red component.
int ft_get_g (int trgb)
Returns the g component of the trgb color. Takes an int representation of a trgb color as parameter. Retuns that color's green component.
int ft_get_b (int trgb)
Returns the b component of the trgb color. Takes an int representation of a trgb color as parameter. Retuns that color's bñue component.
int ft_millis (void)
Returns the milliseconds of the current time of the day. Takes the current time of the day, converts its seconds and microseconds into milliseconds, adds them together and returns them.
Detailed Description
This is libft's most important header file.
The library's main header file!
This header file includes all other headers from this library. It also has the definitions and documentation for most functions in the library.
Todo
Separate stdlibft into multiple sub-sections for improved readability.
Definition in file libft.h.
Macro Definition Documentation
HASHMAP_DEFAULT_SIZE
#define HASHMAP_DEFAULT_SIZE 20
Definition at line 25 of file libft.h.
Referenced by ft_hmap_new().
HASHMAP_MAX_LOAD
#define HASHMAP_MAX_LOAD 0.75f
Definition at line 28 of file libft.h.
Referenced by add_new().
HASHMAP_RESIZE_FACTOR
#define HASHMAP_RESIZE_FACTOR 2
Definition at line 31 of file libft.h.
Referenced by ft_hmap_resize().
Typedef Documentation
t_hashmap
typedef struct s_hashmap t_hashmap
t_key_value
typedef struct s_key_value t_key_value
t_list
typedef struct s_list t_list
t_ushort
typedef unsigned short t_ushort
Definition at line 34 of file libft.h.
Function Documentation
ft_append()
char * ft_append (const char * str, const char * apd, int fr_s, int fr_a)
Definition at line 15 of file ft_append.c.
{
    size_t      strlen;
    char        *result;
    char        *rescopy;
    const char  *strcopy;
    const char  *apdcopy;
    strcopy = str;
    apdcopy = apd;
    strlen = ft_strlen(str) + ft_strlen(apd);
    result = ft_calloc(strlen + 1, sizeof (char));
    if (!result)
        return (NULL);
    rescopy = result;
    while (*strcopy)
        *rescopy++ = *strcopy++;
    while (*apdcopy)
        *rescopy++ = *apdcopy++;
    if (fr_s)
        ft_free((void **) &str);
    if (fr_a)
        ft_free((void **) &apd);
    return (result);
}
References ft_calloc(), ft_free(), and ft_strlen().
Referenced by ft_putendl_fd(), and ft_strinsert().
ft_atoi()
int ft_atoi (const char * str)
Definition at line 15 of file ft_atoi.c.
{
    int     sign;
    long    res;
    sign = 0;
    res = 0;
    while (ft_isspace(*str))
        str++;
    if (*str == '+' || *str == '-')
    {
        if (*str == '-')
            sign = 1;
        str++;
    }
    while (ft_isdigit(*str))
    {
        res += *str - '0';
        if (ft_isdigit(*(str + 1)))
            res *= 10;
        str++;
    }
    if (sign)
        res *= -1;
    return ((int) res);
}
References ft_isdigit(), and ft_isspace().
ft_bzero()
void ft_bzero (void * s, size_t n)
Definition at line 15 of file ft_bzero.c.
{
    unsigned char   *scopy;
    scopy = s;
    while (n)
    {
        if (*scopy != 0)
            *scopy = 0;
        scopy++;
        n--;
    }
}
ft_calloc()
void * ft_calloc (size_t count, size_t size)
Definition at line 15 of file ft_calloc.c.
{
    void    *retbuff;
    void    *retcopy;
    size_t  i;
    retbuff = malloc(count * size);
    if (!retbuff)
        return (NULL);
    retcopy = retbuff;
    i = 0;
    while (i++ < count * size)
    {
        *(unsigned char *) retcopy++ = 0;
    }
    return (retbuff);
}
Referenced by clean_static(), create_return(), ft_append(), ft_hmap_new(), ft_hmap_resize(), ft_itoa(), ft_lstmap(), ft_lstnew(), ft_ltoa(), ft_preppend(), ft_ptr_strnjoin(), ft_split(), ft_strmapi(), ft_substr(), get_next_line(), printbase(), and read_line().
ft_free()
void ft_free (void ** ptr)
Definition at line 15 of file ft_free.c.
{
    if (!*ptr)
        return ;
    free(*ptr);
    *ptr = NULL;
}
Referenced by clean_static(), ft_append(), ft_hmap_resize(), ft_preppend(), ft_putendl_fd(), ft_putnbr_fd(), ft_putsubstr_fd(), get_next_line(), joinfree(), printbase(), printnum(), and read_line().
ft_get_b()
int ft_get_b (int trgb)
Returns the b component of the trgb color. Takes an int representation of a trgb color as parameter. Retuns that color's bñue component.
Parameters
trgb and int representation of the trgb color
Returns
the color's blue component
Definition at line 35 of file ft_trgb.c.
{
    return (trgb & 0xFF);
}
ft_get_g()
int ft_get_g (int trgb)
Returns the g component of the trgb color. Takes an int representation of a trgb color as parameter. Retuns that color's green component.
Parameters
trgb and int representation of the trgb color
Returns
the color's green component
Definition at line 30 of file ft_trgb.c.
{
    return ((trgb >> 8) & 0xFF);
}
ft_get_r()
int ft_get_r (int trgb)
Returns the r component of the trgb color. Takes an int representation of a trgb color as parameter. Retuns that color's red component.
Parameters
trgb and int representation of the trgb color
Returns
the color's red component
Definition at line 25 of file ft_trgb.c.
{
    return ((trgb >> 16) & 0xFF);
}
ft_get_t()
int ft_get_t (int trgb)
Returns the t component of the trgb color. Takes an int representation of a trgb color as parameter. Retuns that color's transparency component.
Parameters
trgb and int representation of the trgb color
Returns
the color's transparency component
Definition at line 20 of file ft_trgb.c.
{
    return ((trgb >> 24) & 0xFF);
}
ft_hash()
t_ushort ft_hash (unsigned char * key, size_t nbytes)
Definition at line 78 of file ft_hmap_mod.c.
{
    int         i;
    t_ushort    hash;
    hash = 0;
    i = 0;
    while (i++ < (int) nbytes)
    {
        hash += *key++;
    }
    return (hash);
}
Referenced by add_new(), ft_hmap_delete(), ft_hmap_edit(), and ft_hmap_get().
ft_hmap_add()
void ft_hmap_add (t_hashmap * hmap, void * key, void * value, size_t len)
Definition at line 17 of file ft_hmap_data_transfer.c.
{
    if (!ft_hmap_get(hmap, key, len))
        add_new(hmap, key, value, len);
    else
        ft_hmap_edit(hmap, key, value, len);
}
References add_new(), ft_hmap_edit(), and ft_hmap_get().
ft_hmap_delete()
void ft_hmap_delete (t_hashmap * hmap, void * key, size_t len)
Definition at line 70 of file ft_hmap_data_transfer.c.
{
    t_ushort    hash;
    t_list      *list;
    t_list      *prev;
    t_key_value *keyval;
    hash = ft_hash((unsigned char *) key, len) % hmap->size;
    list = hmap->map[hash];
    prev = NULL;
    while (list->next != NULL)
    {
        keyval = (t_key_value *) list->content;
        if (ft_strncmp(keyval->key, key, ft_strlen(key)) == 0)
        {
            if (prev != NULL)
                prev->next = list->next;
            ft_lstdelone(list, hmap->del);
            return ;
        }
        prev = list;
        list = list->next;
    }
}
References s_list::content, s_hashmap::del, ft_hash(), ft_lstdelone(), ft_strlen(), ft_strncmp(), s_key_value::key, s_hashmap::map, s_list::next, and s_hashmap::size.
ft_hmap_edit()
void ft_hmap_edit (t_hashmap * hmap, void * key, void * value, size_t len)
Definition at line 50 of file ft_hmap_data_transfer.c.
{
    t_ushort    hash;
    t_list      *list;
    t_key_value *keyval;
    hash = ft_hash((unsigned char *) key, len) % hmap->size;
    list = hmap->map[hash];
    while (list->next != NULL)
    {
        keyval = (t_key_value *) list->content;
        if (ft_strncmp(keyval->key, key, ft_strlen(key)) == 0)
        {
            ((t_key_value *) list->content)->value = value;
            return ;
        }
        list = list->next;
    }
}
References s_list::content, ft_hash(), ft_strlen(), ft_strncmp(), s_key_value::key, s_hashmap::map, s_list::next, and s_hashmap::size.
Referenced by ft_hmap_add().
ft_hmap_free()
void ft_hmap_free (t_hashmap * hmap)
Definition at line 36 of file ft_hmap_mod.c.
{
    int i;
    i = 0;
    while (i < hmap->size)
    {
        if (hmap->map[i] != NULL)
            ft_lstclear(&hmap->map[i], hmap->del);
        i++;
    }
}
References s_hashmap::del, ft_lstclear(), and s_hashmap::map.
Referenced by add_new(), and ft_hmap_resize().
ft_hmap_get()
void * ft_hmap_get (t_hashmap * hmap, void * key, size_t len)
Definition at line 95 of file ft_hmap_data_transfer.c.
{
    t_ushort    hash;
    t_list      *list;
    t_key_value *keyval;
    hash = ft_hash((unsigned char *) key, len) % hmap->size;
    list = hmap->map[hash];
    while (list->next != NULL)
    {
        keyval = (t_key_value *) list->content;
        if (ft_strncmp(keyval->key, key, ft_strlen(key)) == 0)
        {
            return (keyval->value);
        }
        list = list->next;
    }
    return (NULL);
}
References s_list::content, ft_hash(), ft_strlen(), ft_strncmp(), s_key_value::key, s_hashmap::map, s_list::next, s_hashmap::size, and s_key_value::value.
Referenced by ft_hmap_add().
ft_hmap_new()
t_hashmap * ft_hmap_new (void(* del)(void *))
Definition at line 22 of file ft_hmap_mod.c.
{
    t_hashmap   *hmap;
    hmap = malloc(sizeof (t_hashmap));
    if (!hmap)
        return (NULL);
    hmap->del = del;
    hmap->count = 0;
    hmap->size = HASHMAP_DEFAULT_SIZE;
    hmap->map = ft_calloc(HASHMAP_DEFAULT_SIZE, sizeof (t_list));
    return (hmap);
}
References s_hashmap::count, s_hashmap::del, ft_calloc(), HASHMAP_DEFAULT_SIZE, s_hashmap::map, and s_hashmap::size.
ft_hmap_resize()
t_hashmap * ft_hmap_resize (t_hashmap * hmap)
Definition at line 49 of file ft_hmap_mod.c.
{
    t_hashmap   *resized_hmap;
    int         i;
    resized_hmap = malloc(sizeof (t_hashmap));
    if (!resized_hmap)
        return (ft_hmap_free(hmap), NULL);
    resized_hmap->del = hmap->del;
    resized_hmap->count = hmap->count;
    resized_hmap->size = hmap->size * HASHMAP_RESIZE_FACTOR;
    resized_hmap->map = ft_calloc(resized_hmap->size, sizeof (t_list));
    if (!resized_hmap->map)
    {
        ft_hmap_free(hmap);
        ft_hmap_free(resized_hmap);
        return (NULL);
    }
    i = 0;
    while (i < hmap->size)
    {
        resized_hmap->map[i] = hmap->map[i];
        hmap->map[i++] = NULL;
    }
    ft_free((void **)hmap->map);
    ft_free((void **)&hmap);
    return (resized_hmap);
}
References s_hashmap::count, s_hashmap::del, ft_calloc(), ft_free(), ft_hmap_free(), HASHMAP_RESIZE_FACTOR, s_hashmap::map, and s_hashmap::size.
Referenced by add_new().
ft_isalnum()
int ft_isalnum (int c)
Returns 1 if c is an alphanumeric character.
It takes a char as a parameter and if it's an alphanumeric char, meaning it's either a letter or a number, but not a symbol such as $, or another special character, returns true, otherwise it returns false.
Parameters
c the char that will be analyzed
Returns
True or false
Definition at line 15 of file ft_isalnum.c.
{
    return (ft_isalpha(c) || ft_isdigit(c));
}
References ft_isalpha(), and ft_isdigit().
ft_isalpha()
int ft_isalpha (int c)
Returns 1 if c is an alphabetic character.
It takes a char as a parameter and if it's an alphabetic char, meaning a letter, regardless of if it's upper or lowercase, returns true, otherwise it returns false.
Parameters
c the char that will be analyzed
Returns
True or false
Definition at line 15 of file ft_isalpha.c.
{
    return ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z'));
}
Referenced by ft_isalnum().
ft_isascii()
int ft_isascii (int c)
Returns 1 if c is part of the ASCII table.
It takes a char as a parameter and if it's part of the American Standard Code for Information Interchange (ASCII), that is, between 0 and 127, returns true, otherwise it returns false.
Parameters
c the char that will be analyzed
Returns
True or false
Definition at line 15 of file ft_isascii.c.
{
    return (c >= 0 && c <= 127);
}
ft_isdigit()
int ft_isdigit (int c)
Returns 1 if c is a digit (0-9).
It takes a char as a parameter and if it's a digit, returns true, otherwise it returns false.
Parameters
c the char that will be analyzed
Returns
True or false
Definition at line 15 of file ft_isdigit.c.
{
    return (c >= '0' && c <= '9');
}
Referenced by ft_atoi(), and ft_isalnum().
ft_islower()
int ft_islower (int c)
Returns 1 if c is a lowercase letter.
It takes a character c as parameter and if it's a lowercase letter, it returns true, otherwise it returns false.
Parameters
c the char to be analyzed
Returns
True or false
Definition at line 15 of file ft_islower.c.
{
    return (c >= 'a' && c <= 'z');
}
ft_isprint()
int ft_isprint (int c)
Returns 1 if c is a printable character.
It takes a character c as parameter and if it's a printable character, that is, a letter, a digit, or a symbol, it returns true, otherwise it returns false.
Parameters
c the char to be analyzed
Returns
True or false
Definition at line 15 of file ft_isprint.c.
{
    return (c >= ' ' && c <= '~');
}
ft_isspace()
int ft_isspace (int c)
Returns 1 if c is a spacing character.
It takes a character c as parameter and if it's a spacing character (space, tab, newline...), it returns true, otherwise it returns false.
Parameters
c the char to be analyzed
Returns
True or false
Definition at line 15 of file ft_isspace.c.
{
    return (c == ' ' || (c >= '\t' && c <= '\r'));
}
Referenced by ft_atoi().
ft_isupper()
int ft_isupper (int c)
Returns 1 if c is an uppercase letter.
It takes a char as a parameter and if it's an uppercase letter, returns true, otherwise it returns false.
Parameters
c the char that will be analyzed
Returns
True or false
Definition at line 15 of file ft_isupper.c.
{
    return (c >= 'A' && c <= 'Z');
}
ft_itoa()
char * ft_itoa (int n)
Definition at line 17 of file ft_itoa.c.
{
    long    nbr;
    short   ndigits;
    char    *ret;
    nbr = (long) n;
    ndigits = 0;
    while (n > 9 || n < -9)
    {
        ndigits++;
        n /= 10;
    }
    if (nbr < 0)
        ndigits += 3;
    else
        ndigits += 2;
    ret = ft_calloc(ndigits, sizeof (char));
    if (!ret)
        return (NULL);
    if (nbr < 0)
    {
        *ret = '-';
        nbr *= -1;
    }
    recurse_integer(ret + ndigits - 2, nbr);
    return (ret);
}
References ft_calloc(), and recurse_integer().
Referenced by ft_putnbr_fd(), and printnum().
ft_lstadd_back()
void ft_lstadd_back (t_list ** lst, t_list * new_lmn)
Adds an element to the end of the list.
Definition at line 18 of file ft_lstadd_back.c.
{
    t_list  *iter;
    if (!*lst)
    {
        *lst = new_lmn;
        return ;
    }
    iter = *lst;
    while (iter->next != NULL)
    {
        iter = iter->next;
    }
    iter->next = new_lmn;
}
References s_list::next.
Referenced by add_new().
ft_lstadd_front()
void ft_lstadd_front (t_list ** lst, t_list * new_lmn)
Adds an element to the start of the list.
Definition at line 18 of file ft_lstadd_front.c.
{
    new_lmn->next = *lst;
    *lst = new_lmn;
}
References s_list::next.
ft_lstclear()
void ft_lstclear (t_list ** lst, void(* del)(void *))
Definition at line 15 of file ft_lstclear.c.
{
    t_list  *current;
    t_list  *next;
    current = *lst;
    while (current != NULL)
    {
        next = current->next;
        (*del)(current->content);
        free(current);
        current = next;
    }
    *lst = NULL;
}
References s_list::content, and s_list::next.
Referenced by ft_hmap_free(), and ft_lstmap().
ft_lstdelone()
void ft_lstdelone (t_list * lst, void(* del)(void *))
Definition at line 15 of file ft_lstdelone.c.
{
    if (!lst)
        return ;
    (*del)(lst->content);
    free(lst);
}
References s_list::content.
Referenced by ft_hmap_delete().
ft_lstiter()
void ft_lstiter (t_list * lst, void(* f)(void *))
Definition at line 15 of file ft_lstiter.c.
{
    while (lst != NULL)
    {
        (*f)(lst->content);
        lst = lst->next;
    }
}
References s_list::content, and s_list::next.
ft_lstlast()
t_list * ft_lstlast (t_list * lst)
Definition at line 15 of file ft_lstlast.c.
{
    if (!lst)
        return (NULL);
    while (lst->next != NULL)
    {
        lst = lst->next;
    }
    return (lst);
}
References s_list::next.
ft_lstmap()
t_list * ft_lstmap (t_list * lst, void *(* f)(void *), void(* del)(void *))
Definition at line 15 of file ft_lstmap.c.
{
    t_list  *ret;
    t_list  *retcopy;
    if (!lst)
        return (NULL);
    ret = ft_calloc(1, sizeof (t_list));
    if (!ret)
        return (NULL);
    retcopy = ret;
    while (lst != NULL)
    {
        retcopy->content = (*f)(lst->content);
        if (lst->next != NULL)
            retcopy->next = ft_calloc(1, sizeof (t_list));
        else
            break ;
        if (!retcopy->next)
        {
            ft_lstclear(&ret, del);
            return (NULL);
        }
        retcopy = retcopy->next;
        lst = lst->next;
    }
    return (ret);
}
References s_list::content, ft_calloc(), ft_lstclear(), and s_list::next.
ft_lstnew()
t_list * ft_lstnew (void * content)
Definition at line 15 of file ft_lstnew.c.
{
    t_list  *ret;
    ret = ft_calloc(1, sizeof (t_list));
    if (!ret)
        return (NULL);
    ret->content = content;
    return (ret);
}
References s_list::content, and ft_calloc().
Referenced by add_new().
ft_lstsize()
int ft_lstsize (t_list * lst)
Definition at line 15 of file ft_lstsize.c.
{
    int     size;
    size = 0;
    if (!lst)
        return (0);
    while (lst->next != NULL)
    {
        lst = lst->next;
        size++;
    }
    return (size + 1);
}
References s_list::next.
ft_ltoa()
char * ft_ltoa (long n)
Definition at line 17 of file ft_ltoa.c.
{
    long    nbr;
    short   ndigits;
    char    *ret;
    nbr = n;
    ndigits = 0;
    while (n > 9 || n < -9)
    {
        ndigits++;
        n /= 10;
    }
    if (nbr < 0)
        ndigits += 3;
    else
        ndigits += 2;
    ret = ft_calloc(ndigits, sizeof (char));
    if (!ret)
        return (NULL);
    if (nbr < 0)
    {
        *ret = '-';
        nbr *= -1;
    }
    recurse_integer(ret + ndigits - 2, nbr);
    return (ret);
}
References ft_calloc(), and recurse_integer().
ft_memchr()
void * ft_memchr (const void * s, int c, size_t n)
Definition at line 15 of file ft_memchr.c.
{
    unsigned char   ch;
    size_t          str;
    size_t          i;
    ch = (unsigned char) c;
    str = (unsigned long) s;
    i = 0;
    while (i++ < n)
    {
        if (*(unsigned char *)str++ == ch)
            return ((void *)--str);
    }
    return (NULL);
}
ft_memcmp()
int ft_memcmp (const void * s1, const void * s2, size_t n)
Definition at line 15 of file ft_memcmp.c.
{
    size_t          str1;
    size_t          str2;
    size_t          i;
    str1 = (unsigned long) s1;
    str2 = (unsigned long) s2;
    i = 0;
    if (n == 0)
        return (0);
    while (i++ < n)
    {
        if (*(unsigned char *)str1++ != *(unsigned char *)str2++)
            return ((int)(*(unsigned char *)--str1 - *(unsigned char *)--str2));
    }
    return (0);
}
ft_memcpy()
void * ft_memcpy (void * dst, const void * src, size_t n)
Definition at line 15 of file ft_memcpy.c.
{
    unsigned char       *d;
    unsigned const char *s;
    if (dst == src || n == 0)
        return (dst);
    d = dst + n;
    s = src;
    while (n--)
    {
        *(--d) = *(s + n);
    }
    return (dst);
}
ft_memmove()
void * ft_memmove (void * dst, const void * src, size_t n)
Definition at line 15 of file ft_memmove.c.
{
    unsigned char       *d;
    unsigned const char *s;
    size_t              ncopy;
    if ((dst == 0 && src == 0) || n == 0)
        return (dst);
    if (dst > src)
    {
        d = dst + n - 1;
        s = src;
        while (n--)
            *(d--) = *(s + n);
    }
    else
    {
        d = dst;
        s = src;
        ncopy = n - 1;
        while (n--)
            *(d++) = *(s + (ncopy - n));
    }
    return (dst);
}
ft_memset()
void * ft_memset (void * b, int c, size_t len)
Definition at line 15 of file ft_memset.c.
{
    unsigned char   *bcopy;
    bcopy = b;
    while (len)
    {
        *bcopy = (unsigned char) c;
        len--;
        bcopy++;
    }
    return (b);
}
ft_millis()
int ft_millis (void)
Returns the milliseconds of the current time of the day. Takes the current time of the day, converts its seconds and microseconds into milliseconds, adds them together and returns them.
Returns
the milliseconds of the current time of the day
Definition at line 16 of file ft_time.c.
{
    struct timeval  tv;
    gettimeofday(&tv, NULL);
    return (tv.tv_sec * 1000 + tv.tv_usec / 1000);
}
ft_preppend()
char * ft_preppend (const char * str, const char * pre, int fr_s, int fr_p)
Definition at line 15 of file ft_preppend.c.
{
    size_t      strlen;
    char        *result;
    char        *rescopy;
    const char  *strcopy;
    const char  *precopy;
    strcopy = str;
    precopy = pre;
    strlen = ft_strlen(str) + ft_strlen(pre);
    result = ft_calloc(strlen + 1, sizeof (char));
    if (!result)
        return (NULL);
    rescopy = result;
    while (*precopy)
        *rescopy++ = *precopy++;
    while (*strcopy)
        *rescopy++ = *strcopy++;
    if (fr_s)
        ft_free((void **) &str);
    if (fr_p)
        ft_free((void **) &pre);
    return (result);
}
References ft_calloc(), ft_free(), and ft_strlen().
ft_putchar_fd()
int ft_putchar_fd (char c, int fd)
Definition at line 15 of file ft_putchar_fd.c.
{
    write(fd, &c, 1);
    return (1);
}
ft_putendl_fd()
int ft_putendl_fd (const char * s, int fd)
Definition at line 15 of file ft_putendl_fd.c.
{
    char    *s_endl;
    int     ret;
    s_endl = ft_append(s, "\n", 0, 0);
    ret = ft_putstr_fd(s_endl, fd);
    ft_free((void **) &s_endl);
    return (ret);
}
References ft_append(), ft_free(), and ft_putstr_fd().
ft_putnbr_fd()
int ft_putnbr_fd (int n, int fd)
Definition at line 15 of file ft_putnbr_fd.c.
{
    char    *nbr;
    int     ret;
    nbr = ft_itoa(n);
    if (!nbr)
        return (0);
    ret = ft_putstr_fd(nbr, fd);
    ft_free((void **)&nbr);
    return (ret);
}
References ft_free(), ft_itoa(), and ft_putstr_fd().
ft_putstr_fd()
int ft_putstr_fd (const char * s, int fd)
Definition at line 15 of file ft_putstr_fd.c.
{
    int len;
    len = (int) ft_strlen(s);
    write(fd, s, len);
    return (len);
}
References ft_strlen().
Referenced by ft_putendl_fd(), ft_putnbr_fd(), and ft_putsubstr_fd().
ft_putsubstr_fd()
int ft_putsubstr_fd (const char * str, size_t start, size_t end, int fd)
Prints a substring to the designated fd.
Prints a subset of a string to the provided file descriptor. The substring contains all characters from the start position to the end position, both included.
Parameters
str the string from which to print the substring
start the index of the first char of the substring
end the index of the last char of the substring
fd the file destriptor to print to
Returns
The number of characters that where printed to the fd
Definition at line 15 of file ft_putsubstr_fd.c.
{
    char    *sub;
    int     ret;
    if (!str)
        return (0);
    sub = ft_substr(str, start, end - start + 1);
    if (!sub)
        return (0);
    ft_putstr_fd(sub, fd);
    ret = (int) ft_strlen(sub);
    ft_free((void **) &sub);
    return (ret);
}
References ft_free(), ft_putstr_fd(), ft_strlen(), and ft_substr().
ft_split()
char ** ft_split (const char * s, char c)
Definition at line 21 of file ft_split.c.
{
    char        **ret;
    size_t      i;
    size_t      wlen;
    size_t      nwords;
    nwords = count_words((const char **)(size_t) & s, c);
    ret = ft_calloc(nwords, sizeof (char *));
    i = 0;
    wlen = 0;
    while (i++ < nwords - 1 && ret != NULL)
    {
        wlen = word_len(&s, c);
        *ret = ft_calloc(wlen, sizeof (char));
        if (my_free(ret, i))
            return (NULL);
        ft_strlcpy(*ret, s, wlen);
        ret++;
        s += wlen - 1;
    }
    if (ret != NULL)
        ret -= nwords - 1;
    return (ret);
}
References count_words(), ft_calloc(), ft_strlcpy(), my_free(), and word_len().
ft_strchr()
char * ft_strchr (const char * s, int c)
Returns a pointer to the first occurrence of a character.
It takes a string s and a char c as a parameter and searches for the first occurrence of the char c. If it is found it returns a pointer to that character. If it isn't found, it returns a NULL pointer.
Parameters
s the string that will be searched
c the char that will be searched for
Returns
A pointer to the first occurrence of c, or NULL
Definition at line 15 of file ft_strchr.c.
{
    unsigned char   ch;
    int             i;
    ch = (unsigned char) c;
    i = 0;
    while (s[i] != '\0')
    {
        if (s[i] == ch)
            return ((char *)((unsigned long) s + i));
        i++;
    }
    if (ch == '\0')
        return ((char *)((unsigned long) s + i));
    return (NULL);
}
Referenced by ft_strtrim().
ft_strdup()
char * ft_strdup (const char * s1)
Definition at line 15 of file ft_strdup.c.
{
    char    *ret;
    char    *retcopy;
    ret = malloc(ft_strlen(s1) + 1);
    if (!ret)
        return (NULL);
    retcopy = ret;
    while (*s1)
        *retcopy++ = *s1++;
    *retcopy = '\0';
    return (ret);
}
References ft_strlen().
ft_strinsert()
char * ft_strinsert (const char * str, const char * ins, size_t pos)
Definition at line 15 of file ft_strinsert.c.
{
    char    *ret;
    ret = ft_substr(str, 0, pos - 1);
    if (!ret)
        return (NULL);
    ret = ft_append(ret, ins, 1, 0);
    if (!ret)
        return (NULL);
    ret = ft_append(ret, str + pos, 1, 0);
    return (ret);
}
References ft_append(), and ft_substr().
ft_striteri()
char * ft_striteri (char * s, void(* f)(unsigned int, char *))
Definition at line 15 of file ft_striteri.c.
{
    char            *scopy;
    unsigned int    i;
    scopy = s;
    i = 0;
    while (*s)
    {
        (*f)(i++, &*s++);
    }
    return (scopy);
}
ft_strjoin()
char * ft_strjoin (const char * s1, const char * s2)
Definition at line 15 of file ft_strjoin.c.
{
    size_t  total_size;
    char    *ret;
    total_size = ft_strlen(s1) + ft_strlen(s2) + 1;
    ret = malloc(total_size);
    if (!ret)
        return (NULL);
    ft_strlcpy(ret, s1, ft_strlen(s1) + 1);
    ft_strlcat(ret, s2, total_size);
    return (ret);
}
References ft_strlcat(), ft_strlcpy(), and ft_strlen().
ft_strlcat()
size_t ft_strlcat (char * dst, const char * src, size_t dstsize)
Definition at line 15 of file ft_strlcat.c.
{
    size_t  i;
    size_t  dlen;
    size_t  slen;
    i = 0;
    dlen = ft_strlen(dst);
    slen = ft_strlen(src);
    dst += dlen;
    if (dstsize == 0 || dlen >= dstsize)
        return (dstsize + slen);
    while (*src && i++ < dstsize - dlen - 1)
        *dst++ = *src++;
    *dst = '\0';
    return (dlen + slen);
}
References ft_strlen().
Referenced by ft_strjoin().
ft_strlcpy()
size_t ft_strlcpy (char * dst, const char * src, size_t dstsize)
Definition at line 15 of file ft_strlcpy.c.
{
    const char  *s;
    size_t      i;
    s = src;
    i = 0;
    if (dstsize == 0)
        return (ft_strlen(s));
    while (*src && i++ < dstsize - 1)
        *dst++ = *src++;
    *dst = '\0';
    return (ft_strlen(s));
}
References ft_strlen().
Referenced by ft_split(), ft_strjoin(), ft_substr(), and return_result().
ft_strlen()
size_t ft_strlen (const char * s)
Returns the number of characters in the string s.
It takes a string s as a parameter and counts the number of characters thatt string has, then returns it as a size_t (unsigned long).
Parameters
s the string whose length will be measured
Returns
The length of the string
Definition at line 15 of file ft_strlen.c.
{
    size_t  len;
    len = 0;
    while (s && *s++)
        len++;
    return (len);
}
Referenced by clean_static(), create_return(), ft_append(), ft_hmap_delete(), ft_hmap_edit(), ft_hmap_get(), ft_loop(), ft_preppend(), ft_ptr_strnjoin(), ft_putstr_fd(), ft_putsubstr_fd(), ft_strdup(), ft_strjoin(), ft_strlcat(), ft_strlcpy(), ft_strmapi(), ft_strrchr(), ft_strtrim(), ft_substr(), and printstr().
ft_strmapi()
char * ft_strmapi (const char * s, char(* f)(unsigned int, char))
Definition at line 15 of file ft_strmapi.c.
{
    char            *ret;
    unsigned int    i;
    unsigned int    slen;
    slen = ft_strlen(s);
    ret = ft_calloc(slen + 1, sizeof (char));
    if (!ret)
        return (NULL);
    i = 0;
    while (*s)
    {
        *ret++ = (*f)(i++, *s);
        s++;
    }
    ret -= slen;
    return (ret);
}
References ft_calloc(), and ft_strlen().
ft_strncmp()
int ft_strncmp (const char * s1, const char * s2, size_t n)
Definition at line 15 of file ft_strncmp.c.
{
    unsigned long   i;
    i = 0;
    while (*s1 && *s2 && i < n)
    {
        if (*s1 != *s2)
            return ((int)((unsigned char)*s1 - (unsigned char)*s2));
        i++;
        s1++;
        s2++;
    }
    if (n == 0)
        return (0);
    if (i == n)
        return (*--s1 - *--s2);
    return ((int)((unsigned char)*s1 - (unsigned char)*s2));
}
Referenced by ft_hmap_delete(), ft_hmap_edit(), and ft_hmap_get().
ft_strnstr()
char * ft_strnstr (const char * haystack, const char * needle, size_t len)
Definition at line 17 of file ft_strnstr.c.
{
    size_t          i;
    unsigned long   hs;
    char            *found;
    const char      *nd;
    i = 0;
    hs = (unsigned long) haystack;
    if (*needle == '\0' || haystack == needle)
        return ((char *) hs);
    if (*haystack == 0)
        return (NULL);
    while (*(char *)hs != '\0' && ft_loop(i++, len, needle))
    {
        nd = needle;
        found = (char *) hs;
        while (*nd++ == *found++)
            if (*nd == '\0')
                return ((char *) hs);
        hs++;
    }
    return (NULL);
}
References ft_loop().
ft_strrchr()
char * ft_strrchr (const char * s, int c)
Returns a pointer to the last occurrence of a character.
It takes a string s and a char c as a parameter and searches for the last occurrence of the char c. If it is found it returns a pointer to that character. If it isn't found, it returns a NULL pointer.
Parameters
s the string that will be searched
c the char that will be searched for
Returns
A pointer to the last occurrence of c, or NULL
Definition at line 15 of file ft_strrchr.c.
{
    size_t          len;
    size_t          str;
    unsigned char   ch;
    len = ft_strlen(s);
    if (len > 0 && c % 128 != 0)
        len--;
    str = (unsigned long) s;
    ch = (unsigned char) c;
    if (ch == '\0')
        return ((char *)(str + len));
    while ((str + len) >= str)
    {
        if (*(char *)(str + len) == ch)
            return ((char *)(str + len));
        len--;
    }
    return (NULL);
}
References ft_strlen().
ft_strtrim()
char * ft_strtrim (const char * s1, const char * set)
Definition at line 17 of file ft_strtrim.c.
{
    size_t      len;
    char const  *scopy;
    scopy = s1;
    len = ft_strlen(s1);
    if (!*set && !len)
    {
        len++;
        return (return_result(s1, len));
    }
    while (ft_strchr(set, *(scopy + len)) && len > 0)
        len--;
    if (len > 0)
    {
        while (*scopy && ft_strchr(set, *scopy))
            scopy++;
        len -= (size_t) scopy - (size_t) s1 - 1;
    }
    return (return_result(scopy, len + 1));
}
References ft_strchr(), ft_strlen(), and return_result().
ft_substr()
char * ft_substr (const char * s, unsigned int start, size_t len)
Definition at line 17 of file ft_substr.c.
{
    char    *ret;
    size_t  smaller;
    if (*s == '\0' || len == 0 || start >= ft_strlen(s))
    {
        ret = ft_calloc(1, sizeof (char));
        return (ret);
    }
    smaller = ft_smaller(len, ft_strlen(s + start));
    ret = ft_calloc(smaller + 1, sizeof (char));
    if (!ret)
        return (NULL);
    ft_strlcpy(ret, s + start, smaller + 1);
    return (ret);
}
References ft_calloc(), ft_smaller(), ft_strlcpy(), and ft_strlen().
Referenced by ft_putsubstr_fd(), and ft_strinsert().
ft_tolower()
int ft_tolower (int c)
Return the lowercase version of char c.
It takes a character c as parameter and if it's an uppercase letter, it turns it into a lowercase letter and returns it. If it isn't a lowercase letter, it returns it unchanged.
Parameters
c the char to be made into lowercase
Returns
The lowercase character
Definition at line 15 of file ft_tolower.c.
{
    if (c >= 'A' && c <= 'Z')
        return (c + ('a' - 'A'));
    return (c);
}
ft_toupper()
int ft_toupper (int c)
Return the uppercase version of char c.
It takes a character c as parameter and if it's a lowecase letter, it turns it into an uppercase letter and returns it. If it isn't an uppercase letter, it returns it unchanged.
Parameters
c the char to be made into uppercase
Returns
The uppercase character
Definition at line 15 of file ft_toupper.c.
{
    if (c >= 'a' && c <= 'z')
        return (c - ('a' - 'A'));
    return (c);
}
ft_trgb()
int ft_trgb (int t, int r, int g, int b)
Creates an int representation of a trgb color. Takes four int components of a trgb color that must be between 0 and 255. Anything greater will break the function.
Parameters
t the transparency component of the trgb color
r the red component of the trgb color
g the green component of the trgb color
b the blue component of the trgb color
Returns
an int representation of the trgb color
Definition at line 15 of file ft_trgb.c.
{
    return (t << 24 | r << 16 | g << 8 | b);
}