Libft: src/stdlibft/ft_split.c File Reference
ft_split.c File Reference
#include "../include/libft.h"
Functions
static size_t count_words (const char **str, char delimiter)
static size_t word_len (const char **str, char delimiter)
static int my_free (char **ret, size_t i)
char ** ft_split (const char *s, char c)
Function Documentation
count_words()
static size_t count_words (const char ** str, char delimiter) static
Definition at line 47 of file ft_split.c.
{
    size_t      nwords;
    const char  *scopy;
    nwords = 0;
    scopy = *str;
    while (*scopy && *scopy == dlm)
        scopy = scopy + 1;
    if (*scopy != '\0')
    {
        *str = scopy;
        nwords++;
    }
    else
        return (1);
    while (*scopy)
    {
        if (*scopy == dlm && *(scopy + 1) && *(scopy + 1) != dlm)
            nwords++;
        scopy = scopy + 1;
    }
    return (nwords + 1);
}
Referenced by ft_split().
ft_split()
char ** ft_split (const char * s, char c)
Definition at line 21 of file ft_split.c.
{
    char        **ret;
    size_t      i;
    size_t      wlen;
    size_t      nwords;
    nwords = count_words((const char **)(size_t) & s, c);
    ret = ft_calloc(nwords, sizeof (char *));
    i = 0;
    wlen = 0;
    while (i++ < nwords - 1 && ret != NULL)
    {
        wlen = word_len(&s, c);
        *ret = ft_calloc(wlen, sizeof (char));
        if (my_free(ret, i))
            return (NULL);
        ft_strlcpy(*ret, s, wlen);
        ret++;
        s += wlen - 1;
    }
    if (ret != NULL)
        ret -= nwords - 1;
    return (ret);
}
References count_words(), ft_calloc(), ft_strlcpy(), my_free(), and word_len().
my_free()
static int my_free (char ** ret, size_t i) static
Definition at line 88 of file ft_split.c.
{
    size_t  icopy;
    if (*ret != NULL)
        return (0);
    icopy = i;
    while (i > 1)
        free(*(ret - (i-- - 1)));
    free(ret - (icopy - 1));
    return (1);
}
Referenced by ft_split().
word_len()
static size_t word_len (const char ** str, char delimiter) static
Definition at line 72 of file ft_split.c.
{
    size_t  len;
    len = 0;
    while (**str == delimiter)
        *str += 1;
    while (**str && **str != delimiter)
    {
        len++;
        *str += 1;
    }
    *str -= len;
    return (len + 1);
}
Referenced by ft_split().