Libft: src/stdlibft/ft_calloc.c File Reference
ft_calloc.c File Reference
#include "../include/libft.h"
Functions
void * ft_calloc (size_t count, size_t size)
Function Documentation
ft_calloc()
void * ft_calloc (size_t count, size_t size)
Definition at line 15 of file ft_calloc.c.
{
    void    *retbuff;
    void    *retcopy;
    size_t  i;
    retbuff = malloc(count * size);
    if (!retbuff)
        return (NULL);
    retcopy = retbuff;
    i = 0;
    while (i++ < count * size)
    {
        *(unsigned char *) retcopy++ = 0;
    }
    return (retbuff);
}
Referenced by clean_static(), create_return(), ft_append(), ft_hmap_new(), ft_hmap_resize(), ft_itoa(), ft_lstmap(), ft_lstnew(), ft_ltoa(), ft_preppend(), ft_ptr_strnjoin(), ft_split(), ft_strmapi(), ft_substr(), get_next_line(), printbase(), and read_line().