Libft: src/stdlibft/ft_hmap_mod.c File Reference
ft_hmap_mod.c File Reference
#include "../include/libft.h"
Functions
t_hashmap * ft_hmap_new (void(*del)(void *))
void ft_hmap_free (t_hashmap *hmap)
t_hashmap * ft_hmap_resize (t_hashmap *hmap)
t_ushort ft_hash (unsigned char *key, size_t nbytes)
Function Documentation
ft_hash()
t_ushort ft_hash (unsigned char * key, size_t nbytes)
Definition at line 78 of file ft_hmap_mod.c.
{
    int         i;
    t_ushort    hash;
    hash = 0;
    i = 0;
    while (i++ < (int) nbytes)
    {
        hash += *key++;
    }
    return (hash);
}
Referenced by add_new(), ft_hmap_delete(), ft_hmap_edit(), and ft_hmap_get().
ft_hmap_free()
void ft_hmap_free (t_hashmap * hmap)
Definition at line 36 of file ft_hmap_mod.c.
{
    int i;
    i = 0;
    while (i < hmap->size)
    {
        if (hmap->map[i] != NULL)
            ft_lstclear(&hmap->map[i], hmap->del);
        i++;
    }
}
References s_hashmap::del, ft_lstclear(), and s_hashmap::map.
Referenced by add_new(), and ft_hmap_resize().
ft_hmap_new()
t_hashmap * ft_hmap_new (void(* del)(void *))
Definition at line 22 of file ft_hmap_mod.c.
{
    t_hashmap   *hmap;
    hmap = malloc(sizeof (t_hashmap));
    if (!hmap)
        return (NULL);
    hmap->del = del;
    hmap->count = 0;
    hmap->size = HASHMAP_DEFAULT_SIZE;
    hmap->map = ft_calloc(HASHMAP_DEFAULT_SIZE, sizeof (t_list));
    return (hmap);
}
References s_hashmap::count, s_hashmap::del, ft_calloc(), HASHMAP_DEFAULT_SIZE, s_hashmap::map, and s_hashmap::size.
ft_hmap_resize()
t_hashmap * ft_hmap_resize (t_hashmap * hmap)
Definition at line 49 of file ft_hmap_mod.c.
{
    t_hashmap   *resized_hmap;
    int         i;
    resized_hmap = malloc(sizeof (t_hashmap));
    if (!resized_hmap)
        return (ft_hmap_free(hmap), NULL);
    resized_hmap->del = hmap->del;
    resized_hmap->count = hmap->count;
    resized_hmap->size = hmap->size * HASHMAP_RESIZE_FACTOR;
    resized_hmap->map = ft_calloc(resized_hmap->size, sizeof (t_list));
    if (!resized_hmap->map)
    {
        ft_hmap_free(hmap);
        ft_hmap_free(resized_hmap);
        return (NULL);
    }
    i = 0;
    while (i < hmap->size)
    {
        resized_hmap->map[i] = hmap->map[i];
        hmap->map[i++] = NULL;
    }
    ft_free((void **)hmap->map);
    ft_free((void **)&hmap);
    return (resized_hmap);
}
References s_hashmap::count, s_hashmap::del, ft_calloc(), ft_free(), ft_hmap_free(), HASHMAP_RESIZE_FACTOR, s_hashmap::map, and s_hashmap::size.
Referenced by add_new().