Libft: src/stdlibft/ft_itoa.c File Reference
ft_itoa.c File Reference
#include "../include/libft.h"
Functions
static void recurse_integer (char *str, long n)
char * ft_itoa (int n)
Function Documentation
ft_itoa()
char * ft_itoa (int n)
Definition at line 17 of file ft_itoa.c.
{
    long    nbr;
    short   ndigits;
    char    *ret;
    nbr = (long) n;
    ndigits = 0;
    while (n > 9 || n < -9)
    {
        ndigits++;
        n /= 10;
    }
    if (nbr < 0)
        ndigits += 3;
    else
        ndigits += 2;
    ret = ft_calloc(ndigits, sizeof (char));
    if (!ret)
        return (NULL);
    if (nbr < 0)
    {
        *ret = '-';
        nbr *= -1;
    }
    recurse_integer(ret + ndigits - 2, nbr);
    return (ret);
}
References ft_calloc(), and recurse_integer().
Referenced by ft_putnbr_fd(), and printnum().
recurse_integer()
static void recurse_integer (char * str, long n) static
Definition at line 46 of file ft_itoa.c.
{
    if (n > 9)
    {
        recurse_integer(str - 1, n / 10);
        *str = '0' + n % 10;
    }
    else
        *str = '0' + n;
}
References recurse_integer().
Referenced by ft_itoa(), and recurse_integer().