Libft: src/stdlibft/ft_substr.c File Reference
ft_substr.c File Reference
#include "../include/libft.h"
Functions
static size_t ft_smaller (size_t n1, size_t n2)
char * ft_substr (const char *s, unsigned int start, size_t len)
Function Documentation
ft_smaller()
static size_t ft_smaller (size_t n1, size_t n2) static
Definition at line 35 of file ft_substr.c.
{
    if ((long double) n1 <= (long double) n2)
        return (n1);
    return (n2);
}
Referenced by ft_substr().
ft_substr()
char * ft_substr (const char * s, unsigned int start, size_t len)
Definition at line 17 of file ft_substr.c.
{
    char    *ret;
    size_t  smaller;
    if (*s == '\0' || len == 0 || start >= ft_strlen(s))
    {
        ret = ft_calloc(1, sizeof (char));
        return (ret);
    }
    smaller = ft_smaller(len, ft_strlen(s + start));
    ret = ft_calloc(smaller + 1, sizeof (char));
    if (!ret)
        return (NULL);
    ft_strlcpy(ret, s + start, smaller + 1);
    return (ret);
}
References ft_calloc(), ft_smaller(), ft_strlcpy(), and ft_strlen().
Referenced by ft_putsubstr_fd(), and ft_strinsert().