Libft: src/include/ft_printf.h File Reference
ft_printf.h File Reference
#include <stdarg.h>
#include "libft.h"
Functions
int ft_printf (const char *format,...)
void printchar (int *res, int ch)
void printstr (int *res, char *str)
void printnum (int *res, int num)
void printbase (int *res, unsigned int num, int base, int uppercase)
void printptr (int *res, void *ptr)
void recursive_print_digit (int *res, size_t num)
char * capitalize (char *str)
char digit (unsigned int nbr, int base)
char change_letter (char ch)
Function Documentation
capitalize()
char * capitalize (char * str)
Definition at line 15 of file base_format.c.
{
    size_t  i;
    i = 0;
    while (str[i])
    {
        str[i] = change_letter(str[i]);
        i++;
    }
    return (str);
}
References change_letter().
Referenced by printbase().
change_letter()
char change_letter (char ch)
Definition at line 41 of file base_format.c.
{
    if (ch >= '0' && ch <= '9')
        return (ch);
    if (ch >= 'A' && ch <= 'Z')
        ch += 'a' - 'A';
    else
        ch -= 'a' - 'A';
    return (ch);
}
Referenced by capitalize().
digit()
char digit (unsigned int nbr, int base)
Definition at line 28 of file base_format.c.
{
    char            *digits;
    unsigned int    remainder;
    digits = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
    remainder = nbr % base;
    if (remainder <= 9)
        return (remainder + '0');
    else
        return (digits[remainder - 10]);
}
Referenced by printbase(), and recursive_print_digit().
ft_printf()
int ft_printf (const char * format, ...)
Definition at line 17 of file ft_printf.c.
{
    va_list args;
    int     ret;
    va_start(args, format);
    ret = 0;
    while (*format)
    {
        if (*format == '%' && *(format + 1) != '\0')
        {
            parse_conv(*(format + 1), &ret, args);
            format++;
        }
        else if (!(*format == '%' && *(format + 1) == '\0'))
        {
            write(1, format, 1);
            ret++;
        }
        format++;
    }
    va_end(args);
    return (ret);
}
References parse_conv().
printbase()
void printbase (int * res, unsigned int num, int base, int uppercase)
Definition at line 41 of file printchsdixXup.c.
{
    char            *str;
    unsigned int    nbr;
    unsigned short  ndigits;
    nbr = num;
    ndigits = 1;
    while (nbr >= (unsigned int) base)
    {
        nbr /= (unsigned int) base;
        ndigits += 1;
    }
    str = ft_calloc(ndigits + 1, sizeof (char));
    while (ndigits > 0)
    {
        str[--ndigits] = digit(num, base);
        num /= base;
    }
    if (uppercase)
        str = capitalize(str);
    printstr(res, str);
    ft_free((void **) &str);
}
References capitalize(), digit(), ft_calloc(), ft_free(), and printstr().
Referenced by parse_conv().
printchar()
void printchar (int * res, int ch)
Definition at line 15 of file printchsdixXup.c.
{
    write(1, &ch, 1);
    *res += 1;
}
Referenced by parse_conv().
printnum()
void printnum (int * res, int num)
Definition at line 32 of file printchsdixXup.c.
{
    char    *num2str;
    num2str = ft_itoa(num);
    printstr(res, num2str);
    ft_free((void **) &num2str);
}
References ft_free(), ft_itoa(), and printstr().
Referenced by parse_conv().
printptr()
void printptr (int * res, void * ptr)
Definition at line 66 of file printchsdixXup.c.
{
    size_t  ptr2num;
    write(1, "0x", 2);
    *res += 2;
    ptr2num = (size_t) ptr;
    recursive_print_digit(res, ptr2num);
}
References recursive_print_digit().
Referenced by parse_conv().
printstr()
void printstr (int * res, char * str)
Definition at line 21 of file printchsdixXup.c.
{
    int len;
    if (!str)
        str = "(null)";
    len = ft_strlen(str);
    write(1, str, len);
    *res += len;
}
References ft_strlen().
Referenced by parse_conv(), printbase(), and printnum().
recursive_print_digit()
void recursive_print_digit (int * res, size_t num)
Definition at line 52 of file base_format.c.
{
    char    dgt;
    if (num >= 16)
        recursive_print_digit(res, num / 16);
    dgt = digit(num % 16, 16);
    write(1, &dgt, 1);
    *res += 1;
}
References digit(), and recursive_print_digit().
Referenced by printptr(), and recursive_print_digit().