Libft: src/stdlibft/ft_hmap_data_transfer.c File Reference
ft_hmap_data_transfer.c File Reference
#include "../include/libft.h"
Functions
static void add_new (t_hashmap *hmap, void *key, void *value, size_t len)
void ft_hmap_add (t_hashmap *hmap, void *key, void *value, size_t len)
void ft_hmap_edit (t_hashmap *hmap, void *key, void *value, size_t len)
void ft_hmap_delete (t_hashmap *hmap, void *key, size_t len)
void * ft_hmap_get (t_hashmap *hmap, void *key, size_t len)
Function Documentation
add_new()
static void add_new (t_hashmap * hmap, void * key, void * value, size_t len) static
Definition at line 25 of file ft_hmap_data_transfer.c.
{
    t_ushort    hash;
    t_key_value *keyval;
    t_list      *element;
    if (hmap->count + 1 >= hmap->size * HASHMAP_MAX_LOAD)
        hmap = ft_hmap_resize(hmap);
    hmap->count += 1;
    hash = ft_hash((unsigned char *) key, len) % hmap->size;
    if (!hmap->map[hash])
        hmap->map[hash] = ft_lstnew(NULL);
    keyval = malloc(sizeof (t_key_value));
    if (!keyval)
        return (ft_hmap_free(hmap));
    keyval->key = key;
    keyval->value = value;
    element = malloc (sizeof (t_list));
    if (!element)
        return (ft_hmap_free(hmap));
    element->content = keyval;
    element->next = NULL;
    ft_lstadd_back(&hmap->map[hash], element);
}
References s_list::content, s_hashmap::count, ft_hash(), ft_hmap_free(), ft_hmap_resize(), ft_lstadd_back(), ft_lstnew(), HASHMAP_MAX_LOAD, s_key_value::key, s_hashmap::map, s_list::next, s_hashmap::size, and s_key_value::value.
Referenced by ft_hmap_add().
ft_hmap_add()
void ft_hmap_add (t_hashmap * hmap, void * key, void * value, size_t len)
Definition at line 17 of file ft_hmap_data_transfer.c.
{
    if (!ft_hmap_get(hmap, key, len))
        add_new(hmap, key, value, len);
    else
        ft_hmap_edit(hmap, key, value, len);
}
References add_new(), ft_hmap_edit(), and ft_hmap_get().
ft_hmap_delete()
void ft_hmap_delete (t_hashmap * hmap, void * key, size_t len)
Definition at line 70 of file ft_hmap_data_transfer.c.
{
    t_ushort    hash;
    t_list      *list;
    t_list      *prev;
    t_key_value *keyval;
    hash = ft_hash((unsigned char *) key, len) % hmap->size;
    list = hmap->map[hash];
    prev = NULL;
    while (list->next != NULL)
    {
        keyval = (t_key_value *) list->content;
        if (ft_strncmp(keyval->key, key, ft_strlen(key)) == 0)
        {
            if (prev != NULL)
                prev->next = list->next;
            ft_lstdelone(list, hmap->del);
            return ;
        }
        prev = list;
        list = list->next;
    }
}
References s_list::content, s_hashmap::del, ft_hash(), ft_lstdelone(), ft_strlen(), ft_strncmp(), s_key_value::key, s_hashmap::map, s_list::next, and s_hashmap::size.
ft_hmap_edit()
void ft_hmap_edit (t_hashmap * hmap, void * key, void * value, size_t len)
Definition at line 50 of file ft_hmap_data_transfer.c.
{
    t_ushort    hash;
    t_list      *list;
    t_key_value *keyval;
    hash = ft_hash((unsigned char *) key, len) % hmap->size;
    list = hmap->map[hash];
    while (list->next != NULL)
    {
        keyval = (t_key_value *) list->content;
        if (ft_strncmp(keyval->key, key, ft_strlen(key)) == 0)
        {
            ((t_key_value *) list->content)->value = value;
            return ;
        }
        list = list->next;
    }
}
References s_list::content, ft_hash(), ft_strlen(), ft_strncmp(), s_key_value::key, s_hashmap::map, s_list::next, and s_hashmap::size.
Referenced by ft_hmap_add().
ft_hmap_get()
void * ft_hmap_get (t_hashmap * hmap, void * key, size_t len)
Definition at line 95 of file ft_hmap_data_transfer.c.
{
    t_ushort    hash;
    t_list      *list;
    t_key_value *keyval;
    hash = ft_hash((unsigned char *) key, len) % hmap->size;
    list = hmap->map[hash];
    while (list->next != NULL)
    {
        keyval = (t_key_value *) list->content;
        if (ft_strncmp(keyval->key, key, ft_strlen(key)) == 0)
        {
            return (keyval->value);
        }
        list = list->next;
    }
    return (NULL);
}
References s_list::content, ft_hash(), ft_strlen(), ft_strncmp(), s_key_value::key, s_hashmap::map, s_list::next, s_hashmap::size, and s_key_value::value.
Referenced by ft_hmap_add().