Libft: src/get_next_line/get_next_line.c File Reference
get_next_line.c File Reference
#include "../include/get_next_line.h"
Functions
static char * read_line (int fd, char *ret)
Reads the first line of the file pointed to by fd.
static char * create_return (char *str)
Creates a new string that contains only the chars before the '
'.
static char * clean_static (char *str)
Removes all chars before the '
' from the static buffer.
static void joinfree (char **ret, char *str, int chars_read)
Executes strnjoin on ret and str, then swaps it with ret.
char * get_next_line (int fd)
Returns the next line of an opened file.
Function Documentation
clean_static()
static char * clean_static (char * str) static
Removes all chars before the '
' from the static buffer.
This function is executed after create_return, and it will create a new string that only contains the characters after the '
' character from the static buffer, and then returns it.
If the memory allocation fails, or the static buffer is empty, NULL is returned.
Parameters
str the static buffer
Returns
A string with the chars after the '
', if any, else NULL
Definition at line 156 of file get_next_line.c.
{
    char    *ret;
    size_t  i;
    size_t  j;
    i = 0;
    while (str[i] && str[i] != '\n')
        i++;
    if (!str[i])
    {
        ft_free((void **) &str);
        return (NULL);
    }
    ret = ft_calloc(ft_strlen(str) - i + 1, sizeof (char));
    if (!ret)
        return (ft_free((void **) &str), NULL);
    i++;
    j = 0;
    while (str[i])
        ret[j++] = str[i++];
    ft_free((void **) &str);
    return (ret);
}
References ft_calloc(), ft_free(), and ft_strlen().
Referenced by get_next_line().
create_return()
static char * create_return (char * str) static
Creates a new string that contains only the chars before the '
'.
Creates a new string that contains only the characters from the static buffer up to and including the '
' character. If the static buffer contains no '
' the returned string doesn't contain it either.
If the static buffer is empty or the memory allocation fails, NULL is returned.
Parameters
str the static buffer containing the characters read
Returns
a new string containing chars of str up to and including '
'
Definition at line 132 of file get_next_line.c.
{
    char    *ret;
    size_t  i;
    if (*str == '\0')
        return (NULL);
    i = (size_t) ft_idx_strchr(str, '\n') + 2;
    if (i == 1)
        i = ft_strlen(str) + 1;
    ret = ft_calloc(i, sizeof (char));
    if (!ret)
        return (NULL);
    i = 0;
    while (str[i] && str[i] != '\n')
    {
        ret[i] = str[i];
        i++;
    }
    if (str[i] && str[i] == '\n')
        ret[i] = '\n';
    return (ret);
}
References ft_calloc(), ft_idx_strchr(), and ft_strlen().
Referenced by get_next_line().
get_next_line()
char * get_next_line (int fd)
Returns the next line of an opened file.
get_next_line is the main function of the GNL 42Madrid project. It reads a file via a file descriptor and then returns a string with the first line it reads. In an error is encountered, it returns NULL.
Parameters
fd the file descriptor to read from
Returns
The first line of the file pointed by fd
Definition at line 77 of file get_next_line.c.
{
    static char *str;
    char        *ret;
    if (fd < 0 || BUFFER_SIZE <= 0 || read(fd, 0, 0) < 0)
    {
        ft_free((void **) &str);
        return (NULL);
    }
    if (!str)
    {
        str = ft_calloc(BUFFER_SIZE + 1, sizeof (char));
        if (!str)
            return (NULL);
    }
    str = read_line(fd, str);
    if (!str)
        return (NULL);
    ret = create_return(str);
    if (!ret)
        return (ft_free((void **) &str), NULL);
    str = clean_static(str);
    return (ret);
}
References BUFFER_SIZE, clean_static(), create_return(), ft_calloc(), ft_free(), and read_line().
joinfree()
static void joinfree (char ** ret, char * str, int chars_read) static
Executes strnjoin on ret and str, then swaps it with ret.
A new string is created containing the result of joining ret and the chars_read first characters of str. Then the old ret is free'd and ret is assigned this new string.
ret is passed by reference because we need to modify the value of the ret variable in another function, not only in the scope of this function.
Parameters
ret the address of the string that will contain the line read
str a string containing the characters read by the read()
chars_read the number of characters read by read()
Definition at line 181 of file get_next_line.c.
{
    char    *swap;
    swap = ft_ptr_strnjoin(*ret, str, chars_read);
    ft_free((void **) ret);
    if (swap)
        *ret = swap;
}
References ft_free(), and ft_ptr_strnjoin().
Referenced by read_line().
read_line()
static char * read_line (int fd, char * ret) static
Reads the first line of the file pointed to by fd.
This function takes a file descriptor and attempts to read it in BUFFER_SIZE increments until either an error, the EOF, or a '
' character is encountered. If no errors were encountered, the line that was read is stored in the static buffer ret. At this point, ret may contain extra chars after the '
' which need to be cleaned at a later stage.
If an error is encountered, all buffers are free'd and set to NULL, and NULL is returned.
Parameters
fd a file descriptor that points to the file to be read
ret the static buffer in which the line will be stored
Returns
The static line containing the line that was read
Definition at line 103 of file get_next_line.c.
{
    char    *str;
    int     chars_read;
    str = ft_calloc((BUFFER_SIZE + 1), sizeof (char));
    if (!str)
        return (ft_free((void **) &ret), NULL);
    chars_read = 1;
    while (chars_read > 0)
    {
        chars_read = read(fd, str, BUFFER_SIZE);
        if (!chars_read)
            break ;
        if (chars_read == -1)
        {
            ft_free((void **) &str);
            ft_free((void **) &ret);
            return (NULL);
        }
        if (ret && str)
            joinfree(&ret, str, chars_read);
        if (ft_idx_strchr(str, '\n') + 1 != 0)
            break ;
    }
    ft_free((void **) &str);
    return (ret);
}
References BUFFER_SIZE, ft_calloc(), ft_free(), ft_idx_strchr(), and joinfree().
Referenced by get_next_line().