Libft: src/ft_printf/base_format.c File Reference
base_format.c File Reference
#include "../include/ft_printf.h"
Functions
char * capitalize (char *str)
char digit (unsigned int nbr, int base)
char change_letter (char ch)
void recursive_print_digit (int *res, size_t num)
Function Documentation
capitalize()
char * capitalize (char * str)
Definition at line 15 of file base_format.c.
{
    size_t  i;
    i = 0;
    while (str[i])
    {
        str[i] = change_letter(str[i]);
        i++;
    }
    return (str);
}
References change_letter().
Referenced by printbase().
change_letter()
char change_letter (char ch)
Definition at line 41 of file base_format.c.
{
    if (ch >= '0' && ch <= '9')
        return (ch);
    if (ch >= 'A' && ch <= 'Z')
        ch += 'a' - 'A';
    else
        ch -= 'a' - 'A';
    return (ch);
}
Referenced by capitalize().
digit()
char digit (unsigned int nbr, int base)
Definition at line 28 of file base_format.c.
{
    char            *digits;
    unsigned int    remainder;
    digits = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
    remainder = nbr % base;
    if (remainder <= 9)
        return (remainder + '0');
    else
        return (digits[remainder - 10]);
}
Referenced by printbase(), and recursive_print_digit().
recursive_print_digit()
void recursive_print_digit (int * res, size_t num)
Definition at line 52 of file base_format.c.
{
    char    dgt;
    if (num >= 16)
        recursive_print_digit(res, num / 16);
    dgt = digit(num % 16, 16);
    write(1, &dgt, 1);
    *res += 1;
}
References digit(), and recursive_print_digit().
Referenced by printptr(), and recursive_print_digit().